fix: update k3s yml

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -38,12 +38,17 @@ jobs:
           elif echo "$FIRST_LINE" | grep -q "OPENSSH PRIVATE KEY"; then
             mv $HOME/.ssh/temp_key $HOME/.ssh/id_ed25519
             KEY_FILE="$HOME/.ssh/id_ed25519"
-            # Convert key to PEM format
-            ssh-keygen -p -f $HOME/.ssh/id_ed25519 -m PEM -N "" -P ""
           else
             echo "Unsupported key type"
             exit 1
           fi
+
+          ssh-keygen -lf $KEY_FILE || {
+            NEW_HEAD=$(head -n 2 $KEY_FILE | cut -c 1-40)
+            echo "Invalid SSH key: $NEW_HEAD"
+            echo "Invalid SSH key"
+            exit 1
+          }
 
           ssh-keyscan -H ${{ secrets.SSH_HOST }} >> $HOME/.ssh/known_hosts
 
