temp

diff --git a/.github/workflows/prod.yml b/.github/workflows/prod.yml
--- a/.github/workflows/prod.yml
+++ b/.github/workflows/prod.yml
@@ -39,9 +39,9 @@ jobs:
         continue-on-error: true
         run: |
           ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
-          mkdir -p ${{ secrets.PROD_WORK_DIR }} \
-          && cd ${{ secrets.PROD_WORK_DIR }} \
-          && rm -rf ${{ env.REPOSITORY_NAME }}"
+          mkdir -p ${{ secrets.PROD_WORK_DIR }} && \
+          cd ${{ secrets.PROD_WORK_DIR }} && \
+          rm -rf ${{ env.REPOSITORY_NAME }}"
 
       - name: Copy the repository files to the server
         run: |
@@ -50,22 +50,22 @@ jobs:
       - name: Kubernetes - Create namespaces
         run: |
           ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
-          cd ${{ secrets.PROD_WORK_DIR }}/${{ env.REPOSITORY_NAME }} \
-          && make k-create-namespaces || true"
+          cd ${{ secrets.PROD_WORK_DIR }}/${{ env.REPOSITORY_NAME }} && \
+          make k-create-namespaces || true"
 
       - name: Kubernetes - Create PV and PVC
         continue-on-error: true
         run: |
           ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
-          cd ${{ secrets.PROD_WORK_DIR }}/${{ env.REPOSITORY_NAME }} \
-          && make k-apply-volume-prod || true"
+          cd ${{ secrets.PROD_WORK_DIR }}/${{ env.REPOSITORY_NAME }} && \
+          make k-apply-volume-prod || true"
 
       - name: Kubernetes - Delete secrets
         run: |
           ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
-          kubectl delete secret ghcr-secret --namespace ${{ env.NAMESPACE }} || true \
-          && kubectl delete secret api-tls-secret --namespace ${{ env.NAMESPACE }} || true \
-          && kubectl delete secret admin-tls-secret --namespace ${{ env.NAMESPACE }} || true"
+          kubectl delete secret ghcr-secret --namespace ${{ env.NAMESPACE }} || true && \
+          kubectl delete secret api-tls-secret --namespace ${{ env.NAMESPACE }} || true && \
+          kubectl delete secret admin-tls-secret --namespace ${{ env.NAMESPACE }} || true"
 
       - name: Kubernetes - Create secrets
         run: |
@@ -78,22 +78,22 @@ jobs:
           rm api.crt api.key admin.crt admin.key
 
           ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
-          cd ${{ secrets.PROD_WORK_DIR }}/${{ env.REPOSITORY_NAME }} \
-          && set -e \
-          && kubectl create secret generic api-tls-secret --namespace=${{ env.NAMESPACE }} \
-          --type=kubernetes.io/tls --from-file=tls.crt=api.crt --from-file=tls.key=api.key \
-          && rm -f api.crt api.key \
-          && kubectl create secret generic admin-tls-secret --namespace=${{ env.NAMESPACE }} \
-          --type=kubernetes.io/tls --from-file=tls.crt=admin.crt --from-file=tls.key=admin.key \
-          && rm -f admin.crt admin.key"
+          cd ${{ secrets.PROD_WORK_DIR }}/${{ env.REPOSITORY_NAME }} && \
+          set -e && \
+          kubectl create secret generic api-tls-secret --namespace=${{ env.NAMESPACE }} \
+          --type=kubernetes.io/tls --from-file=tls.crt=api.crt --from-file=tls.key=api.key && \ 
+          rm -f api.crt api.key  && \
+          kubectl create secret generic admin-tls-secret --namespace=${{ env.NAMESPACE }} \
+          --type=kubernetes.io/tls --from-file=tls.crt=admin.crt --from-file=tls.key=admin.key && \
+          rm -f admin.crt admin.key"
 
       - name: Kubernetes - Delete config map
         run: |
           ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
-          kubectl delete configmap postgres-env-config --namespace ${{ env.NAMESPACE }} || echo 'postgres-env-config already exists or failed!' \
-          && kubectl delete configmap redis-env-config --namespace ${{ env.NAMESPACE }} || echo 'redis-env-config already exists or failed!' \
-          && kubectl delete configmap api-env-config --namespace ${{ env.NAMESPACE }} || echo 'api-env-config already exists or failed!' \
-          && kubectl delete configmap api-jwt-config --namespace ${{ env.NAMESPACE }} || echo 'api-jwt-config already exists or failed!'"
+          kubectl delete configmap postgres-env-config --namespace ${{ env.NAMESPACE }} || echo 'postgres-env-config already exists or failed!' && \
+          kubectl delete configmap redis-env-config --namespace ${{ env.NAMESPACE }} || echo 'redis-env-config already exists or failed!' && \
+          kubectl delete configmap api-env-config --namespace ${{ env.NAMESPACE }} || echo 'api-env-config already exists or failed!' && \
+          kubectl delete configmap api-jwt-config --namespace ${{ env.NAMESPACE }} || echo 'api-jwt-config already exists or failed!'"
 
       - name: Kubernetes - Create config map
         run: |
@@ -107,45 +107,45 @@ jobs:
           rm postgres.env redis.env app.env private.pem public.pem
 
           ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
-          cd ${{ secrets.PROD_WORK_DIR }}/${{ env.REPOSITORY_NAME }} \
-          && set -e \
-          && kubectl create configmap postgres-env-config --from-env-file=postgres.env --namespace ${{ env.NAMESPACE }} \
-          && kubectl create configmap redis-env-config --from-env-file=redis.env --namespace ${{ env.NAMESPACE }} \
-          && kubectl create configmap api-env-config --from-file=app.env --namespace ${{ env.NAMESPACE }} \
-          && kubectl create configmap api-jwt-config --from-file=private.pem --from-file=public.pem --namespace ${{ env.NAMESPACE }}"
+          cd ${{ secrets.PROD_WORK_DIR }}/${{ env.REPOSITORY_NAME }} && \
+          set -e && \
+          kubectl create configmap postgres-env-config --from-env-file=postgres.env --namespace ${{ env.NAMESPACE }} && \
+          kubectl create configmap redis-env-config --from-env-file=redis.env --namespace ${{ env.NAMESPACE }} && \
+          kubectl create configmap api-env-config --from-file=app.env --namespace ${{ env.NAMESPACE }} && \
+          kubectl create configmap api-jwt-config --from-file=private.pem --from-file=public.pem --namespace ${{ env.NAMESPACE }}"
 
       - name: Kubernetes - Apply deployments
         run: |
           ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
-          cd ${{ secrets.PROD_WORK_DIR }}/${{ env.REPOSITORY_NAME }} \
-          && set -e \
-          && make k-apply-deploy-redis-prod \
-          && make k-apply-deploy-postgres-prod \
-          && make k-apply-deploy-api-prod \
-          && make k-apply-deploy-admin-prod"
+          cd ${{ secrets.PROD_WORK_DIR }}/${{ env.REPOSITORY_NAME }} && \
+          set -e && \
+          make k-apply-deploy-redis-prod && \
+          make k-apply-deploy-postgres-prod && \
+          make k-apply-deploy-api-prod && \
+          make k-apply-deploy-admin-prod"
 
       - name: Kubernetes - Apply services
         run: |
           ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
-          cd ${{ secrets.PROD_WORK_DIR }}/${{ env.REPOSITORY_NAME }} \
-          && set -e \
-          && kubectl apply -f ./kubernetes/services/redis.yml --namespace ${{ env.NAMESPACE }} \
-          && kubectl apply -f ./kubernetes/services/postgres.yml --namespace ${{ env.NAMESPACE }} \
-          && kubectl apply -f ./kubernetes/services/api.yml --namespace ${{ env.NAMESPACE }} \
-          && kubectl apply -f ./kubernetes/services/admin.yml --namespace ${{ env.NAMESPACE }}"
+          cd ${{ secrets.PROD_WORK_DIR }}/${{ env.REPOSITORY_NAME }} && \
+          set -e && \
+          kubectl apply -f ./kubernetes/services/redis.yml --namespace ${{ env.NAMESPACE }} && \
+          kubectl apply -f ./kubernetes/services/postgres.yml --namespace ${{ env.NAMESPACE }} && \
+          kubectl apply -f ./kubernetes/services/api.yml --namespace ${{ env.NAMESPACE }} && \
+          kubectl apply -f ./kubernetes/services/admin.yml --namespace ${{ env.NAMESPACE }}"
 
       - name: Kubernetes - Apply middlewares
         run: |
           ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
-          cd ${{ secrets.STAGING_WORK_DIR }}/${{ env.REPOSITORY_NAME }} \
-          && set -e \
-          && kubectl apply -f ./kubernetes/middlewares/sslredirect.yml"
+          cd ${{ secrets.PROD_WORK_DIR }}/${{ env.REPOSITORY_NAME }} && \
+          set -e && \
+          kubectl apply -f ./kubernetes/middlewares/sslredirect.yml"
 
       - name: Kubernetes - Apply ingress
         run: |
           ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
-          cd ${{ secrets.PROD_WORK_DIR }}/${{ env.REPOSITORY_NAME }} \
-          && make k-apply-ingress-prod"
+          cd ${{ secrets.PROD_WORK_DIR }}/${{ env.REPOSITORY_NAME }} && \
+          make k-apply-ingress-prod"
 
       - name: Cleanup SSH dir
         run: rm -rf ~/.ssh
