fix

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -41,8 +41,11 @@ jobs:
       - name: Remove old project files from server
         continue-on-error: true
         run: |
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ${{ secrets.STAGING_WORK_DIR }}"
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIR }} && rm -rf school-deployment && exit"
+          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
+            mkdir -p ${{ secrets.STAGING_WORK_DIR }}
+            cd ${{ secrets.STAGING_WORK_DIR }}
+            rm -rf school-deployment
+          EOF
 
       - name: Copy the repository files to the server
         run: |
@@ -64,15 +67,16 @@ jobs:
       - name: Kubernetes - Deleting secret ingress [2/2]
         continue-on-error: true
         run: |
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "kubectl delete secret admin-env-secret --namespace ${{ env.NAMESPACE }} && exit"
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "kubectl delete secret api-tls-secret --namespace ${{ env.NAMESPACE }} && exit"
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "kubectl delete secret admin-tls-secret --namespace ${{ env.NAMESPACE }} && exit"
+          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
+            kubectl delete secret admin-env-secret --namespace ${{ env.NAMESPACE }} || true
+            kubectl delete secret api-tls-secret --namespace ${{ env.NAMESPACE }} || true
+            kubectl delete secret admin-tls-secret --namespace ${{ env.NAMESPACE }} || true
+          EOF
 
-      - name: Kubernetes - Update secrets
+      - name: Kubernetes - Create secrets
         run: |
           ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment && kubectl create secret docker-registry ghcr-secret --namespace ${{ env.NAMESPACE }} --docker-server=https://ghcr.io --docker-username=${{secrets.GHCR_USERNAME}} --docker-password=${{secrets.GHCR_PASSWORD}} --docker-email=${{secrets.GHCR_EMAIL}} && exit"
-
-          # ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment && kubectl create secret generic admin-env-secret --namespace ${{ env.NAMESPACE }} --from-literal=APP_ENV="staging"  && exit"
+          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment && kubectl create secret generic admin-env-secret --namespace ${{ env.NAMESPACE }} --from-literal=APP_ENV="staging"  && exit"
 
           echo "$API_TLS_CERT" > api.crt
           echo "$API_TLS_KEY" > api.key
@@ -82,21 +86,37 @@ jobs:
           scp -P 22 -i ~/.ssh/id_rsa api.crt api.key admin.crt admin.key ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.STAGING_WORK_DIR }}/school-deployment
           rm api.crt api.key admin.crt admin.key
           
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment && kubectl create secret generic api-tls-secret --namespace=${{ env.NAMESPACE }} --type=kubernetes.io/tls --from-file=tls.crt=api.crt --from-file=tls.key=api.key && exit"
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment && rm api.crt api.key && exit"
+          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
+            cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment
 
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment && kubectl create secret generic admin-tls-secret --namespace=${{ env.NAMESPACE }} --type=kubernetes.io/tls --from-file=tls.crt=admin.crt --from-file=tls.key=admin.key && exit"
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment && rm admin.crt admin.key && exit"
-      
-      - name: Kubernetes - Deleting config map
+            kubectl create secret generic api-tls-secret \
+              --namespace=${{ env.NAMESPACE }} \
+              --type=kubernetes.io/tls \
+              --from-file=tls.crt=api.crt \
+              --from-file=tls.key=api.key || echo "api-tls-secret already exists or failed!"
+
+            rm -f api.crt api.key
+
+            kubectl create secret generic admin-tls-secret \
+              --namespace=${{ env.NAMESPACE }} \
+              --type=kubernetes.io/tls \
+              --from-file=tls.crt=admin.crt \
+              --from-file=tls.key=admin.key || echo "admin-tls-secret already exists or failed!"
+
+            rm -f admin.crt admin.key
+          EOF
+
+      - name: Kubernetes - Delete config map
         continue-on-error: true
         run: |
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "kubectl delete configmap postgres-env-config --namespace ${{ env.NAMESPACE }} && exit"
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "kubectl delete configmap redis-env-config --namespace ${{ env.NAMESPACE }} && exit"
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "kubectl delete configmap api-env-config --namespace ${{ env.NAMESPACE }} && exit"
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "kubectl delete configmap api-jwt-config --namespace ${{ env.NAMESPACE }} && exit"
+          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
+            kubectl delete configmap postgres-env-config --namespace ${{ env.NAMESPACE }} || echo "postgres-env-config already exists or failed!"
+            kubectl delete configmap redis-env-config --namespace ${{ env.NAMESPACE }} || echo "redis-env-config already exists or failed!"
+            kubectl delete configmap api-env-config --namespace ${{ env.NAMESPACE }} || echo "api-env-config  already exists or failed!"
+            kubectl delete configmap api-jwt-config --namespace ${{ env.NAMESPACE }} || echo "api-jwt-config already exists or failed!"
+          EOF
 
-      - name: Kubernetes - Update config map
+      - name: Kubernetes - Create config map
         continue-on-error: true
         run: |
           echo "$POSTGRES_ENV" > postgres.env
@@ -108,24 +128,35 @@ jobs:
           scp -P 22 -i ~/.ssh/id_rsa postgres.env redis.env api.env private.pem public.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.STAGING_WORK_DIR }}/school-deployment
           rm postgres.env redis.env api.env private.pem public.pem
 
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "kubectl create configmap postgres-env-config --from-env-file=postgres.env --namespace ${{ env.NAMESPACE }} && exit"
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "kubectl create configmap redis-env-config --from-env-file=redis.env --namespace ${{ env.NAMESPACE }} && exit"
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "kubectl create configmap api-env-config --from-file=app.env --namespace ${{ env.NAMESPACE }} && exit"
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "kubectl create configmap api-jwt-config --from-file=private.pem --from-file=public.pem --namespace ${{ env.NAMESPACE }} && exit"
+          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
+            kubectl create configmap postgres-env-config --from-env-file=postgres.env --namespace ${{ env.NAMESPACE }} || echo "postgres-env-config already exists or failed!"
+            kubectl create configmap redis-env-config --from-env-file=redis.env --namespace ${{ env.NAMESPACE }} || echo "redis-env-config already exists or failed!"
+            kubectl create configmap api-env-config --from-file=app.env --namespace ${{ env.NAMESPACE }} || echo "api-env-config already exists or failed!"
+            kubectl create configmap api-jwt-config \
+              --from-file=private.pem \
+              --from-file=public.pem \
+              --namespace ${{ env.NAMESPACE }} || echo "api-jwt-config already exists or failed!"
+          EOF
 
       - name: Kubernetes - Apply deployments
         run: |
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment && make k-apply-deploy-redis-staging && exit"
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment && make k-apply-deploy-postgres-staging && exit"
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment && make k-apply-deploy-api-staging && exit"
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment && make k-apply-deploy-admin-staging && exit"
+          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
+            cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment
+            make k-apply-deploy-redis-staging
+            make k-apply-deploy-postgres-staging
+            make k-apply-deploy-api-staging
+            make k-apply-deploy-admin-staging
+          EOF
 
       - name: Kubernetes - Apply services
         run: |
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment && kubectl apply -f ./kubernetes/services/redis.yml --namespace ${{ env.NAMESPACE }} && exit"
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment && kubectl apply -f ./kubernetes/services/postgres.yml --namespace ${{ env.NAMESPACE }} && exit"
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment && kubectl apply -f ./kubernetes/services/api.yml --namespace ${{ env.NAMESPACE }} && exit"
-          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment && kubectl apply -f ./kubernetes/services/admin.yml --namespace ${{ env.NAMESPACE }} && exit"
+          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
+            cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment
+            kubectl apply -f ./kubernetes/services/redis.yml --namespace ${{ env.NAMESPACE }}
+            kubectl apply -f ./kubernetes/services/postgres.yml --namespace ${{ env.NAMESPACE }}
+            kubectl apply -f ./kubernetes/services/api.yml --namespace ${{ env.NAMESPACE }}
+            kubectl apply -f ./kubernetes/services/admin.yml --namespace ${{ env.NAMESPACE }}
+          EOF
 
       - name: Kubernetes - Apply ingress
         run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.STAGING_WORK_DIR }}/school-deployment && make k-apply-ingress-staging && exit"
